### ISSUE TITLE
Review configuration interface

### ISSUE THREAD

**Issue by davidcemin** [AVnu/Open-AVB#115] opened 2014-10-31 13:25 UTC
Current configuration interface is done through switches upon gPTP initialization. Improve the current one to support more parameters. 

Here the current configuration switches we have:
./daemon_cl <network interface> [-S] [-P] [-M <filename>] [-A <count>] [-G <group>] [-R <priority 1>]
	-S start syntonization
	-P pulse per second
	-M <filename> save/restore state
	-A <count> initial accelerated sync count
	-G <group> group id for shared memory
	-R <priority 1> priority 1 value
	-T force master
	-L force slave

We could embed that on a gPTP.cfg and read this file on its initialization. Eventually we will need more parameters, as for instance the phy delay, which currently has to be manually set on a define (and hence recompile the gPTP). Code below:

linux/src/linux_hal_generic.cpp:52:#define TX_PHY_TIME 184
linux/src/linux_hal_generic.cpp:53:#define RX_PHY_TIME 382
linux/src/linux_hal_generic.cpp:55://#define TX_PHY_TIME 8000
linux/src/linux_hal_generic.cpp:56://#define RX_PHY_TIME 8000

**Comment by andrew-elder** [comment] 2015-06-25 15:59
Need more details David....

**Comment by davidcemin** [comment] 2015-06-25 17:50
Andrew, please take a look now.

**Comment by andrew-elder** [comment] 2015-06-25 18:01
Thanks. .cfg file sounds like a good idea.

**Comment by andrew-elder** [comment] 2015-07-09 15:04
Duplicate of issue#253

**Comment by davidcemin** [comment] 2015-10-05 20:22
If we put the default configuration from daemon_cl in a file called lets say gPTP.cfg, we would have something like below.

The idea would be starting the daemon using the file as another option, as for instance:

daemon_cl eth0 -f gPTP.cfg.

# Default command line parameters
sintonize               = true
pulse_per_second        = false
accelerated_sync_count  = 0
override_port_state     = false
port_state              = PTP_MASTER
priority1               = 248
restore_state			= false
restore_state_file      = restore.dat
ipc_groupname           = ptp

# PHY Ingress/Egress delay in nanoseconds
tx_phy_time     = 184
rx_phy_time     = 382

**Closed** 2016-03-16 18:37 UTC
Labels: duplicate, fixed, gPTP, will_fix
