### ISSUE TITLE
gPTP.com.c.5.4, offsetScaledLogVariance

### ISSUE THREAD

**Issue by andrew-elder** [AVnu/Open-AVB#131] opened 2014-11-07 12:56 UTC
gPTP.com.c.5.4, offsetScaledLogVariance is reported as 0x4100

**Comment by davidcemin** [comment] 2015-10-21 20:57
The problem is fixed by changing it to 0x436A

**Comment by andrew-elder** [comment] 2015-10-21 21:09
Great

**Closed** 2016-03-16 18:40 UTC
Labels: bug, fixed, gPTP, will_fix
